### ISSUE TITLE
 I broke the game

### ISSUE THREAD

**Issue by rcnerd** [KRHS-GameProgramming-2015/Epic-Pong#3]
I was able to set the paddles so that the ball bounced back and forth forever. May have to be solved with a random with very small effect.
![capture](https://cloud.githubusercontent.com/assets/12915987/12853897/97d140f8-cc04-11e5-8978-ecc3b3ce5467.PNG)

**Comment by MrLe3578** [comment]
Most people would get bored enough and just move it out of the continuous cycle.
